### ISSUE TITLE
Add hyperlinks to keywords in sos->html

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-docs#46] opened 2019-01-11 15:11 UTC
This will require some work, but i think it would be helpful if we can parse and add links to text for conversion of sos->html. For example for a workflow:

```
[*_1]
input:  ..., group_by = ...
```

We will potentially add 3 links `*_`, `input:` and `group_by` each pointing to a relevant tutorial page.

**Comment by BoPeng** [comment] 2019-01-11 15:47
This can potentially be done through JS, which identifies a pre-defined set of keyword and mark them. A quick google search shows https://www.jqueryscript.net/text/Auto-Link-Keywords-jQuery-linkit.html but there should more such tools out there.

**Comment by BoPeng** [comment] 2019-01-22 18:23
Template added. For example, go to 

https://vatlab.github.io/sos-docs/doc/user_guide/named_output.html

wait for a few seconds (for unresolved tech reasons), find any `input:`, and place cursor on it, clicking will take to the doc.

Right now only `input:` works, but more links will be added to https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/parts/hover_doc.tpl#L31

**Comment by BoPeng** [comment] 2019-01-22 20:52
@jma7 I am assigning this ticket to you. 

What is happening is that I am creating a template that finds keyword in the HTML file and use a tooltip like mechanism to allow user to visit our tutorials from relevant keyword. 

The code in [this template](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/parts/hover_doc.tpl), which should be pretty easy to understand.Basically I just create a [simple `div` ](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/parts/hover_doc.tpl#L4), and [find codemirror highlighted keywords](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/parts/hover_doc.tpl#L65) and add events to them. The problem is that when the doc is loaded, codemirror has not finished syntax highlighting, so unless I [wait for a few seconds](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/parts/hover_doc.tpl#L63), the script will not work.

What I want to do is to make sure that the scanning happens after codemirror highlights the code [here](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/parts/cm.tpl#L83). The problem with codemirror is that it needs some time to run so I have to use a [setTimeOutput](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/parts/cm.tpl#L56) to highlight cells one by one, otherwise the thread will be killed by the browser. I will need to

1. Change the chained `setTimeout` to a chained promise.
2. Scan the notebook after all cells have been highlighted.

**Comment by BoPeng** [comment] 2019-01-22 20:58
To test this, install  trunk of `sos-notebook` and run

```
sos convert /path/to/sos-docs/src/user_guide/named_output.ipynb result.html --template sos-doc
```

**Comment by BoPeng** [comment] 2019-01-22 22:43
@jma7 I had this `#sos_hover_tooltip` thing to mimic tooltip but there is no need to have this `div`, adding the styles to `.sos_hover_doc` is good enough.

**Comment by BoPeng** [comment] 2019-01-23 05:33
Completed tutorials on `input`, `output`, and `depends` statements and linked `input:` and `output:` and `depends:` to them. The benefit of these summary tutorials is that they provide quick summaries of things can be done with these statements so that users can checkout specific tutorials for in-depth information.

**Comment by BoPeng** [comment] 2019-01-23 15:59
@jma7 I fixed the css of this template so the only thing remaining is the `setTimeout` stuff.

**Comment by jma7** [comment] 2019-01-23 21:48
@BoPeng Made a fix on codemirror branch, please check to see if the behavior is what you want, I will clean up and merge upon your approval.

**Comment by BoPeng** [comment] 2019-01-23 21:53
But then the codemirror code will be run twice? It make sense however to merge the doc template to the codemirror template and let the downstream template decide if they want both (cm + doc) or one (cm).

**Comment by BoPeng** [comment] 2019-01-23 22:23
So in summary perhaps we can move `hover_doc.tpl` to `sos/templates/parts`.

1. create `sos/templates/parts`
2. move `sos/templates/sos-mode.js` to `sos/templates/parts`
3. create `sos/templates/parts/hover_doc.tpl` with at least definitions of keyword and links
3. copy `sos_notebook/templates/parts/cm.tpl` to `sos/templates/parts`, in this template we provide macros for `cm`, `cm + keyword` for plain HTML, used by `sos/templates/sos_script.tpl`.
4. Modify `sos_notebook/templates/parts/cm.tpl` (rename to `cm_notebook.tpl`?) to provide macros to `cm` and `cm+keyword` for notebooks, used by `sos_notebook/templates/sos-doc.tpl`.

**Comment by BoPeng** [comment] 2019-01-24 00:33
No. We have templates that are oriented for users who do not need to know how sos works so the clicking event is not needed. Generally speaking I would like to add the event to `sos-script`, which is a HTML file with just the script, and `sos-doc`, which is used for sos documentation.

Also, I think the long list of HTML should be replaced by a pivotal URL, something like 

```
http://vatlab.github.io/sos-doc/search?key=name
```
which would point to the URLs in the file. In this way we are free to update our documentation without breaking old HTML pages with these links.

**Comment by jma7** [comment] 2019-01-24 04:59
Not sure what is the long list of URLs...in which file?

**Comment by BoPeng** [comment] 2019-01-24 05:08
I was saying [these URLs](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/parts/hover_doc.tpl#L19) should be generated as something like:

```
window.open('https://vatlab.github.io/sos-docs/search?' + evt.target.innerText, '_blank')
```
and we put the URLs in this page as redirects.

**Comment by BoPeng** [comment] 2019-01-24 05:11
Also jinja2 macros support parameters so instead of two macros for codemirror w/wo keyword links we can have a single macro and include it as something like

```
cm(with_keyword_links=true)
```

**Comment by BoPeng** [comment] 2019-01-24 21:51
@jma7 `setTimeout` does not seem to be needed at [this line](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/parts/cm.tpl#L88) according to my local examples. Also, what are [this](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/parts/cm.tpl#L61) and [this](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/parts/cm.tpl#L80) for? Please remove them if not needed.

**Comment by BoPeng** [comment] 2019-01-24 22:33
Ok, I think this part of the work is done. Basically,

1. [hover_doc.tpl](https://github.com/vatlab/SoS/blob/master/src/sos/templates/parts/hover_doc.tpl) defines the feature that is currently used in [sos-scripts.tpl](https://github.com/vatlab/SoS/blob/master/src/sos/templates/sos_script.tpl#L70) and [sos-doc.tpl](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/templates/sos-doc.tpl#L4)

2. The template highlights [all the keywords](https://github.com/vatlab/SoS/blob/master/src/sos/templates/parts/hover_doc.tpl#L17) and clicking the keyword will open website `https://vatlab.github.io/sos-docs/redirect_doc.html?KEYWORD`.

3. [The redirect_doc page](https://github.com/vatlab/sos-docs/blob/master/redirect_doc.html#L6) simply direct the keyword to its documentation. Right now only a few of the links are defined so most of the keywords will lead to `user_guide.html`. We will update this page as we adjust our documentation.

**Comment by BoPeng** [comment] 2020-01-09 20:41
redirect page updated with all keywords.

**Closed by BoPeng** 2020-01-09 20:41 UTC
