### ISSUE TITLE
`LP_Mixed_ST.sos` example no longer works

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-docs#23] opened 2018-02-25 20:34 UTC
Not sure if the problem can be reproduced but I suspect it is related to recent changes to file lock codes. These examples under `src/examples` no long work:

```
./LP_Mixed_ST.sos
./LP_Mixed.sos
```

They simply hang at the first step. 

(Please pull the repo for a couple of typo fixes.)

**Comment by BoPeng** [comment] 2018-02-25 20:40
Will have a look. Is this the last example?

**Comment by BoPeng** [comment] 2018-02-25 21:07
I still see

```
output: "data_${id}.train.csv", "data_${id}.test.csv"
```
which should be fixed. Although hanging should be fixed.

**Comment by gaow** [comment] 2018-02-25 21:23
> Will have a look. Is this the last example?

Yes it is the last example. Sorry I have to fix that ...

**Comment by BoPeng** [comment] 2018-02-25 21:41
The problem was caused by mismatch `provides` and `output`,

```
[simulation: provides = ["data_{id}.train.csv", "data_{id}.test.csv"]]
output: "data_${id}.train.csv", "data_${id}.test.csv"
```
The patch produces an error for this case.

**Closed** 2018-03-04 03:24 UTC
